#===========================================#
#{ONLINE} Shows the number of players online
#{MAXONLINE} Show the number of max player online
#{PLAYERNAME} Shows player's name
#===========================================#
LINE1: "§bWelcome to §l§5Mythical§9PE§2 Jungle Realm!"
LINE2: "             §8-===+===-"
LINE3: "§bThis is a §l§5Mythical§9PE§r§b Factions Server!"
LINE4: "§bTo get a starter kit, do §e/kit starter§b!"
LINE5: "§bTo start a faction, do §e/f create§b!"
LINE6: "§bWant to support the server? Donate at §eEnchantedRealms.buycraft.net"
LINE7: "§bIf you purchase a rank on this realm, you'll recieve access to new commands and more!"
LINE8: "§bWant to pvp? Jump off of §e/spawn§b or go to §e/warp pvp§b!"
LINE9: "§bThe forums link is §eERPE.enjin.com"
LINE10: "§7There are a total of §l§e{ONLINE} §r§7players out of §l§e{MAXONLINE}"
#Coordinates
Xs: 108
Ys: 93
Zs: 153
